name: QCA-ALL

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动追加插件包'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{ matrix.CONFIG }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFINO]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: OpenWRT
      WRT_IP: 192.168.1.1
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ github.event.inputs.PACKAGE }}
      WRT_TEST: ${{ github.event.inputs.TEST || 'false' }}